// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Location struct {
	ID          string
	Name        string
	Description string
}

type Room struct {
	ID         string
	LocationID string
	Name       string
	ImagePath  string
}

type Scp struct {
	ID               string
	Name             string
	ContainmentClass string
	Description      string
	Lore             string
}
