// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const getSCP = `-- name: GetSCP :one
SELECT id, name, containment_class, description, lore FROM scps WHERE id = ?
`

func (q *Queries) GetSCP(ctx context.Context, id string) (Scp, error) {
	row := q.db.QueryRowContext(ctx, getSCP, id)
	var i Scp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContainmentClass,
		&i.Description,
		&i.Lore,
	)
	return i, err
}

const listLocations = `-- name: ListLocations :many
SELECT id, name, description FROM locations ORDER BY id
`

func (q *Queries) ListLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.QueryContext(ctx, listLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomsForLocation = `-- name: ListRoomsForLocation :many
SELECT id, location_id, name, image_path FROM rooms WHERE location_id = ? ORDER BY id
`

func (q *Queries) ListRoomsForLocation(ctx context.Context, locationID string) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRoomsForLocation, locationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.LocationID,
			&i.Name,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSCPs = `-- name: ListSCPs :many
SELECT id, name, containment_class, description, lore FROM scps ORDER BY id
`

func (q *Queries) ListSCPs(ctx context.Context) ([]Scp, error) {
	rows, err := q.db.QueryContext(ctx, listSCPs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Scp
	for rows.Next() {
		var i Scp
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContainmentClass,
			&i.Description,
			&i.Lore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLocation = `-- name: UpsertLocation :exec
INSERT OR IGNORE INTO locations (id, name, description)
VALUES (?, ?, ?)
`

type UpsertLocationParams struct {
	ID          string
	Name        string
	Description string
}

func (q *Queries) UpsertLocation(ctx context.Context, arg UpsertLocationParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocation, arg.ID, arg.Name, arg.Description)
	return err
}

const upsertRoom = `-- name: UpsertRoom :exec
INSERT OR IGNORE INTO rooms (id, location_id, name, image_path)
VALUES (?, ?, ?, ?)
`

type UpsertRoomParams struct {
	ID         string
	LocationID string
	Name       string
	ImagePath  string
}

func (q *Queries) UpsertRoom(ctx context.Context, arg UpsertRoomParams) error {
	_, err := q.db.ExecContext(ctx, upsertRoom,
		arg.ID,
		arg.LocationID,
		arg.Name,
		arg.ImagePath,
	)
	return err
}

const upsertSCP = `-- name: UpsertSCP :exec
INSERT OR IGNORE INTO scps (id, name, containment_class, description, lore)
VALUES (?, ?, ?, ?, ?)
`

type UpsertSCPParams struct {
	ID               string
	Name             string
	ContainmentClass string
	Description      string
	Lore             string
}

func (q *Queries) UpsertSCP(ctx context.Context, arg UpsertSCPParams) error {
	_, err := q.db.ExecContext(ctx, upsertSCP,
		arg.ID,
		arg.Name,
		arg.ContainmentClass,
		arg.Description,
		arg.Lore,
	)
	return err
}
